/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rybak (https://sketchfab.com/rybak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/longclaw-838d895a8bff406cb2da6104bed69900
Title: Longclaw
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useFrame } from "@react-three/fiber";

export default function Staff(props) {
  const { nodes, materials } = useGLTF("/models/staff-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[3, 3, 3]}
        position={[0.5, 0.5, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/staff-transformed.glb");
