/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useFrame } from "@react-three/fiber";

export default function Wizard(props) {
  const { nodes, materials } = useGLTF("/models/wizard-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y = -2 + Math.sin(state.clock.elapsedTime) * 0.15;
    modelRef.current.rotation.y = Math.sin(state.clock.elapsedTime) * 1;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.3, 0.3, 0.3]}
      rotation={[-0.2, 0, 0]}
      position={[-0.2, 0, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube000.geometry}
        material={materials["sword.001"]}
        position={[1.522, 8.425, -2.046]}
        rotation={[0.717, -0.867, -0.702]}
        scale={[0.329, 4.134, 0.104]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.furs}
        position={[-0.179, 12.834, -0.46]}
        rotation={[0.223, 0.927, -0.226]}
        scale={[1.547, 0.577, 1.272]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.face}
        position={[0, 14.302, 0]}
        scale={[1.23, 1.001, 1.122]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.cape}
        position={[-0.139, 12.919, -0.518]}
        scale={[1.547, 0.577, 1.272]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.sword}
        position={[1.522, 8.425, -2.046]}
        rotation={[0.717, -0.867, -0.702]}
        scale={[0.329, 4.134, 0.104]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.bot}
        position={[-1.617, 1.004, 1.577]}
        rotation={[0.037, 0.503, -0.082]}
        scale={[0.523, 0.494, 0.902]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.body}
        position={[0.71, 8.664, -5.053]}
        rotation={[-1.538, -0.647, 0.077]}
        scale={[0.064, 0.067, 0.271]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.hair}
        position={[0.479, 15.293, -0.715]}
        rotation={[2.506, 0.125, -1.783]}
        scale={0.24}
      />
    </group>
  );
}

useGLTF.preload("/models/wizard-transformed.glb");
